### ISSUE TITLE
Flashbang not stunning players properly

### ISSUE THREAD

**Issue by GenericUsername27** [Juansero29/SFDScripts#41]
![FlashbangBug](https://user-images.githubusercontent.com/76974284/111882429-d2950700-89b5-11eb-8ce5-0d4c439a2f20.gif)

Sometimes players will not get stunned even though they are in range of the flashbang.

This bug is independent of the amount of players, but highly dependent on the position of the player, so it took me a few tries to reproduce it.

Not sure if this is a priority right now.

**Comment by Juansero29** [comment]
Yep, this is definetly a bug. It should be solved. I'm marking it as part of the support milestone for April the 15th.
